import { type NextPage } from "next";
import Head from "next/head";
import Item from "../components/Item";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const sections = api.checklist.getSections.useQuery({ id: "HELOO" });

  return (
    <>
      <Head>
        <title>repeatlist</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto max-w-2xl">
          <p className="my-10 text-center">repeatlist</p>
          <h1 className="bold mb-4 text-center text-2xl font-bold">
            How to Reach Flow Easily
          </h1>
          {sections.data?.map((section, idx) => (
            <div
              key={idx}
              className="mb-6 rounded-md border border-solid border-gray-200"
            >
              <div className="border-b py-3 px-4">
                <h2 className="text-lg font-semibold text-gray-800">
                  {section.title}
                </h2>
              </div>
              <div className="px-4">
                {section.tasks.map((task, idx) => (
                  <Item
                    key={idx}
                    title={task.title}
                    done={false}
                    description={task.description}
                    isFirst={idx !== 0}
                  />
                ))}
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
