import { type NextPage } from "next";
import Head from "next/head";
import Item from "../components/Item";

import { api } from "../utils/api";

const tasks = [
  {
    title: "Step 1 is to do this",
    done: true,
  },
  {
    title: "Step is then this",
    done: false,
  },
  {
    title: "Step is then this",
    done: false,
  },
  {
    title: "Step is then this",
    done: false,
  },
  {
    title: "Step is then this",
    done: false,
  },
];

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>repeatlist</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto max-w-2xl">
          <p className="my-10 text-center">repeat.so</p>
          <h1 className="bold mb-4 text-xl font-bold">How to do a task</h1>
          <div className="rounded-md border border-solid border-gray-200 px-4">
            {tasks.map((task, idx) => (
              <Item
                key={idx}
                title={task.title}
                done={task.done}
                isFirst={idx !== 0}
              />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
