import { type NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-20">
        <div className="relative z-20 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-xl text-center">
            <h1 className="text-4xl font-bold">
              Create and distribute checklists for anything
            </h1>
            <p className="mt-5 text-base sm:text-xl">
              Share your procedures with whoever you like.
            </p>
          </div>
          <div className="mt-8 flex flex-col items-center justify-center">
            <Link href="/new">
              <Button>Create my checklist now</Button>
            </Link>
            <p className="text-sm text-gray-500">10 free checklists per user</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
