import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Brand } from "../components/Brand";
import Button from "../components/Button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RepeatList: Reusable Checklist Templates</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="mx-auto max-w-6xl px-4">
          <div className="flex h-16 items-center justify-between gap-8">
            <div className="flex items-center gap-8">
              <Brand />
              <div>
                <ul className="flex">
                  {navLinks.map((link) => (
                    <li key={link.path}>
                      <Link
                        className="px-4 py-2 text-gray-500 transition-colors hover:text-black"
                        href={link.path}
                      >
                        {link.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
            <div className="flex gap-1">
              <Button variant="text">Log In</Button>
              <Button variant="outline">Create my account</Button>
            </div>
          </div>
        </div>
      </header>
      <main>
        <section>
          <div className="mx-auto max-w-6xl px-4 pt-28">
            <div className="grid grid-cols-12">
              <div className="col-span-5">
                <h1 className="mt-3 text-5xl font-bold">
                  Make lightning strike twice with checklist templates
                </h1>
                <p className="mt-5 text-lg">
                  Sometimes a reusable checklist is all you need to ensure your
                  processes yield perfection every single time.
                </p>
                <div className="mt-4 w-fit">
                  <Link href={"/new"}>
                    <Button>Create a checklist now – FREE</Button>
                  </Link>
                  <p className="mt-2 text-sm text-gray-500">
                    No account required.
                  </p>
                </div>
              </div>
              <div className="col-span-7">
                <div className="relative">
                  <Image
                    src={"/visual.png"}
                    alt="laptop and phone showing different checklists"
                    width={1576}
                    height={929}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="mx-auto max-w-6xl px-4">
            <h2 className="mt-32 text-center text-3xl font-semibold">
              Use cases
            </h2>
            <div></div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;

const navLinks = [
  {
    label: "Pricing",
    path: "/pricing",
  },
  {
    label: "Use cases",
    path: "#use-cases",
  },
  {
    label: "Features",
    path: "#features",
  },
];
