import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RepeatList | Slogan goes here and shit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="mx-auto max-w-6xl">
          <div className="flex">
            <div className="relative h-8 w-auto">
              <Image
                src="/full-brand.png"
                alt="logo"
                fill
                quality={100}
                style={{ objectFit: "contain" }}
              />
            </div>
            <div>
              <ul className="flex">
                <li>Pricing</li>
                <li>Features</li>
                <li>Blog</li>
              </ul>
            </div>
          </div>
        </div>
      </header>
    </>
  );
};

export default Home;
